id is:axfydk47
Launching wandb...
[36m(RLRunner pid=669090)[39m Exception raised in creation task: The actor died because of an error raised in its creation task, [36mray::RLRunner.__init__()[39m (pid=669090, ip=10.1.123.172, actor_id=3e02bc48d75db6087c59a57a01000000, repr=<runner.RLRunner object at 0x7f5e86440a50>)
[36m(RLRunner pid=669090)[39m            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[36m(RLRunner pid=669090)[39m            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[36m(RLRunner pid=669090)[39m   File "/home/ubuntu/LNS2-RL/runner.py", line 285, in __init__
[36m(RLRunner pid=669090)[39m     super().__init__(meta_agent_id)
[36m(RLRunner pid=669090)[39m   File "/home/ubuntu/LNS2-RL/runner.py", line 43, in __init__
[36m(RLRunner pid=669090)[39m     self.env.save_rgb_image(os.path.join(self.output_dir, "step_000.png"))
[36m(RLRunner pid=669090)[39m                                          ^^^^^^^^^^^^^^^
[36m(RLRunner pid=669090)[39m AttributeError: 'RLRunner' object has no attribute 'output_dir'
Saving Final Model !